# Generated by Django 4.0.3 on 2022-03-23 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_user_invitation_alter_user_invite_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='invite_code',
            field=models.CharField(default='H1033J', max_length=6),
        ),
    ]
