# Generated by Django 4.0.3 on 2022-03-23 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_user_invite_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AlterField(
            model_name='user',
            name='invite_code',
            field=models.CharField(default='O7HEL6', max_length=6),
        ),
    ]
